### PR TITLE
fix windows update

### LINKED ISSUE #55: "failed to run temp binary" on Windows
Hello 👋

Thanks for the great library. It was simple to get it implemented in our code base. We have it working successfully on Mac but I'm running into a bit of trouble on Windows. We're using the HTTP fetcher which is downloading the file and placing it in a temp directory successfully (can see it show up in file explorer). But when the fetch process tries to see if the downloaded binary is executable it returns an error and bails out:

`failed to run temp binary: exec: "C:\\Users\\Level\\AppData\\Local\\Temp\\overseer-1dc5f76e2b9039ce": file does not exist (C:\Users\Level\AppData\Local\Temp\overseer-1dc5f76e2b9039ce) output ""`

The file certainly does exist but for some reason Go thinks it doesn't. The error is coming from this line: https://github.com/jpillora/overseer/blob/6877a7e73f6a4bebbfe1999fcbf84e52a3c1e6ca/proc_master.go#L287

image

Does anyone have any experience or advice related to this error? Thanks!

### PR DESCRIPTION
**Pull request by audiolion**
The tmpBinPath did not have the .exe extension on Windows which would cause the update to fail because Windows only considers files that correlate with the PATHEXT variable and that does not include no extension files.

Closes #55

### CODE REVIEW

File: proc_master.go [hunk 1]
```diff
@@ -426,3 +427,12 @@ func token() string {
 	rand.Read(buff)
 	return hex.EncodeToString(buff)
 }
+
+// On Windows, include the .exe extension, noop otherwise.
+func extension() string {
```
Comment (audiolion) [inline proc_master.go:432]: It was recommended to place this in an `init` function in `proc_windows_slave.go`, but I think this is more clear. `proc_windows_slave.go` works incidentally, the file itself does not use `tmpBinPath` and is the `_slave`, not `_master` file. If there were a `proc_master_windows.go` I could see a better argument, but even then I feel that this is more explicit about what is happening.

Comment (jpillora) [reply proc_master.go:432]: Agreed, avoid init where possible 👍

**Comment by jpillora** [comment]
Merged! Thanks :)

**Comment by jpillora** [comment]
Tagged `v1.1.6`

**Comment by joshforbes** [comment]
wow thanks for merging it so quick @jpillora. Awesome.
